# Generated by Django 3.0.5 on 2020-05-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_comfirmed', models.DateField()),
                ('case_number', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=127)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(default='Hong Kong', max_length=20)),
                ('x_coord', models.DecimalField(decimal_places=4, max_digits=22, null=True)),
                ('y_coord', models.DecimalField(decimal_places=4, max_digits=22, null=True)),
                ('detail', models.CharField(blank=True, max_length=127, null=True)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.CaseRecord')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.LocationRecord')),
            ],
        ),
    ]
