# Generated by Django 3.0.5 on 2020-05-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationrecord',
            name='district',
            field=models.CharField(default='Central and Western', max_length=20),
        ),
    ]
