# Generated by Django 3.0.5 on 2020-05-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_userrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
